### ISSUE TITLE
Paradrop discussion

### ISSUE THREAD

**Issue by Cuel** [fparma/comfy-downtime#2]
I personally don't like how players can just paradrop right back on top of everyone else. What about a check so that you can't paradrop within 300m of enemy AI?

**Comment by ComfyPillow** [comment]
Sounds good.

I will look into putting in a restriction to not allow them to teleport too close to enemies.
Probably gonna make the restriction default and offer an option to disable it if needed.

**Comment by WhiteFox08** [comment]
Proposed in #7
